export function getDataCardsEasy() {
  return [
    // Amarelo

    {
      id: 1,
      phrase: "QUAL O MOMENTO MAIS ALEGRE DA SUA VIDA?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 2,
      phrase: "ADULTO SENTE ALEGRIA?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 3,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 4,
      phrase: "VOCÊ JÁ VIU ALGUÉM ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 5,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 6,
      phrase: "O QUE TE DEIXA ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },

    //AZUL
    {
      id: 7,
      phrase: "QUAL O MOMENTO MAIS TRISTE DA SUA VIDA?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 8,
      phrase: "ADULTOS SENTE TRISTEZA?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 9,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ  TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 10,
      phrase: "VOCÊ JÁ VIU ALGUÉM TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 11,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 12,
      phrase: "O QUE VOCÊ FAZ QUANDO ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 13,
      phrase: "O QUE TE DEIXA TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 14,
      phrase: "O QUE FAZ VOCÊ SE SENTIR MELHOR QUANDO ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 15,
      phrase: "COMO AJUDAR ALGUÉM QUE ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },

    //VERMELHO
    {
      id: 16,
      phrase: "QUAL O MOMENTO DA SUA VIDA EM QUE VOCÊ MAIS SENTIU RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 17,
      phrase: "ADULTO SENTE RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 18,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 19,
      phrase: "VOCÊ JÁ VIU ALGUÉM COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 20,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 232320,
      phrase: "O QUE VOCÊ FAZ QUANDO ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 21,
      phrase: "O QUE TE DEIXA COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 22,
      phrase: "O QUE FAZ VOCÊ SE SENTIR MELHOR QUANDO VOCÊ ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 23,
      phrase: "COMO AJUDAR ALGUÉM QUE ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },

    //ROXO
    {
      id: 24,
      phrase: "QUAL O MOMENTO DA SUA VIDA EM QUE VOCÊ MAIS SENTIU MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 25,
      phrase: "ADULTO SENTE MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 11212312312,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 1133332312312,
      phrase: "VOCÊ JÁ VIU ALGUÉM COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 3312,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 33122121,
      phrase: "O QUE VOCÊ FAZ QUANDO ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 212313122312,
      phrase: "O QUE TE DEIXA COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 27,
      phrase: "O QUE FAZ VOCÊ SE SENTIR MELHOR QUANDO ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 28,
      phrase: "COMO AJUDAR ALGUÉM QUE ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
  ];
}

export function getDataCardsMedium() {
  return [
    // Amarelo

    {
      id: 1,
      phrase: "QUAL O MOMENTO MAIS ALEGRE DA SUA VIDA?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 2,
      phrase: "ADULTO SENTE ALEGRIA?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 3,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 4,
      phrase: "VOCÊ JÁ VIU ALGUÉM ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 5,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },
    {
      id: 6,
      phrase: "O QUE TE DEIXA ALEGRE?",
      points: 22,
      idColor: 0,
      isSelected: false,
    },

    //AZUL
    {
      id: 7,
      phrase: "QUAL O MOMENTO MAIS TRISTE DA SUA VIDA?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 8,
      phrase: "ADULTOS SENTE TRISTEZA?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 9,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ  TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 10,
      phrase: "VOCÊ JÁ VIU ALGUÉM TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 11,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 12,
      phrase: "O QUE VOCÊ FAZ QUANDO ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 13,
      phrase: "O QUE TE DEIXA TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 14,
      phrase: "O QUE FAZ VOCÊ SE SENTIR MELHOR QUANDO ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },
    {
      id: 15,
      phrase: "COMO AJUDAR ALGUÉM QUE ESTÁ TRISTE?",
      points: 22,
      idColor: 1,
      isSelected: false,
    },

    //VERMELHO
    {
      id: 16,
      phrase: "QUAL O MOMENTO DA SUA VIDA EM QUE VOCÊ MAIS SENTIU RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 17,
      phrase: "ADULTO SENTE RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 18,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 19,
      phrase: "VOCÊ JÁ VIU ALGUÉM COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 20,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 232320,
      phrase: "O QUE VOCÊ FAZ QUANDO ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 21,
      phrase: "O QUE TE DEIXA COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 22,
      phrase: "O QUE FAZ VOCÊ SE SENTIR MELHOR QUANDO VOCÊ ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },
    {
      id: 23,
      phrase: "COMO AJUDAR ALGUÉM QUE ESTÁ COM RAIVA?",
      points: 22,
      idColor: 2,
      isSelected: false,
    },

    //ROXO
    {
      id: 24,
      phrase: "QUAL O MOMENTO DA SUA VIDA EM QUE VOCÊ MAIS SENTIU MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 25,
      phrase: "ADULTO SENTE MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 11212312312,
      phrase: "COMO VOCÊ SABE QUE ALGUÉM ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 1133332312312,
      phrase: "VOCÊ JÁ VIU ALGUÉM COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 3312,
      phrase: "COMO VOCÊ SABE QUE VOCÊ ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 33122121,
      phrase: "O QUE VOCÊ FAZ QUANDO ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 212313122312,
      phrase: "O QUE TE DEIXA COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 27,
      phrase: "O QUE FAZ VOCÊ SE SENTIR MELHOR QUANDO ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },
    {
      id: 28,
      phrase: "COMO AJUDAR ALGUÉM QUE ESTÁ COM MEDO?",
      points: 22,
      idColor: 3,
      isSelected: false,
    },

    //ROSA
    {
      id: 29,
      phrase: "O QUE É EMPATIA?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 30,
      phrase: "COMO PRATICAR A EMPATIA?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 31,
      phrase: "O QUE É GRATIDÃO?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 32,
      phrase: "COMO PRATICAR A GRATIDÃO?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 33,
      phrase: "O QUE É O PERDÃO?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 34,
      phrase: "O QUE É O AMOR?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 35,
      phrase: "QUAL O MOMENTO DA SUA VIDA EM QUE VOCÊ MAIS SE SENTIU AMADO?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 36,
      phrase: "O QUE É ESPERANÇA PARA VOCÊ?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 37,
      phrase: "VOCÊ JÁ SENTIU GRATIDÃO POR ALGUMA COISA?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 38,
      phrase: "VOCÊ JÁ SENTIU EMPATIA POR ALGUÉM?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 39,
      phrase: "VOCÊ JÁ PERDOOU ALGUÉM?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 40,
      phrase:
        "ALGUÉM JÁ TE AGRADECEU POR ALGUMA COISA? COMO VOCÊ SE SENTIU COM ISSO?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 41,
      phrase: "ALGUÉM JÁ FOI EMPÁTICO COM VOCÊ?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },
    {
      id: 42,
      phrase: "VOCÊ JÁ PERDOOU ALGUÉM?",
      points: 22,
      idColor: 4,
      isSelected: false,
    },

    //VERDE
    {
      id: 43,
      phrase: "COMO VOCÊ SABE QUE ESTÁ FRUSTRADO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 44,
      phrase: "COMO VOCÊ SABE QUE ESTÁ COM NOJO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 45,
      phrase: "COMO VOCÊ SABE QUE ESTÁ COM TÉDIO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 46,
      phrase: "COMO VOCÊ SABE QUE ESTÁ MAGOADO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 47,
      phrase: "VOCÊ JÁ SE SENTIU FRUSTRADO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 48,
      phrase: "VOCÊ JÁ SENTIU NOJO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 49,
      phrase: "VOCÊ JÁ SENTIU TÉDIO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 50,
      phrase: "VOCÊ JÁ SENTIU MÁGOA?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 51,
      phrase: "VOCÊ JÁ MAGOOU ALGUÉM?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 52,
      phrase: "QUAL A FUNÇÃO DO NOJO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 53,
      phrase: "O QUE TE FAZ SAIR DO TÉDIO?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
    {
      id: 54,
      phrase: "O QUE FAZER QUANDO VOCÊ MAGOA ALGUÉM?",
      points: 22,
      idColor: 5,
      isSelected: false,
    },
  ];
}
